# -*- coding: utf-8 -*-
"""Python.Armstrong Number

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NZEwE3lsEH6Cur_HRkDtrtwHQhyBrvtm
"""

while True :

  number = input("enter a positive number : ")
  digits = len(number)
  summ = 0
  if not number.isdigit() :
     print(number,"is invalid entry.Enter valid input")
  elif int(number) >= 0 :
      for i in range(digits) :
           summ = summ + int(number[i])  ** digits
      if summ == int(number):
            print(number,"is an Armstrong number")
            break
      else :
        print(number,"is not an Armstrong number")
        break